"""Solana Chain Heat contracts for Printer V1 Phase 8."""

from enum import StrEnum


class ChainHeatLabel(StrEnum):
    SOLANA_HOT = "SOLANA_HOT"
    SOLANA_WARM = "SOLANA_WARM"
    SOLANA_NEUTRAL = "SOLANA_NEUTRAL"
    SOLANA_COOL = "SOLANA_COOL"
    SOLANA_COLD = "SOLANA_COLD"
    SOLANA_CONGESTED = "SOLANA_CONGESTED"
    SOLANA_QUIET = "SOLANA_QUIET"
    SOLANA_UNKNOWN = "SOLANA_UNKNOWN"


class SolanaActivityLabel(StrEnum):
    ACTIVITY_SURGING = "ACTIVITY_SURGING"
    ACTIVITY_ELEVATED = "ACTIVITY_ELEVATED"
    ACTIVITY_NORMAL = "ACTIVITY_NORMAL"
    ACTIVITY_WEAK = "ACTIVITY_WEAK"
    ACTIVITY_DEAD = "ACTIVITY_DEAD"
    ACTIVITY_UNKNOWN = "ACTIVITY_UNKNOWN"


class SolanaLiquidityLabel(StrEnum):
    LIQUIDITY_EXPANDING = "LIQUIDITY_EXPANDING"
    LIQUIDITY_STABLE = "LIQUIDITY_STABLE"
    LIQUIDITY_THINNING = "LIQUIDITY_THINNING"
    LIQUIDITY_STRESSED = "LIQUIDITY_STRESSED"
    LIQUIDITY_UNKNOWN = "LIQUIDITY_UNKNOWN"


class SolanaCongestionLabel(StrEnum):
    CONGESTION_LOW = "CONGESTION_LOW"
    CONGESTION_NORMAL = "CONGESTION_NORMAL"
    CONGESTION_HIGH = "CONGESTION_HIGH"
    CONGESTION_SEVERE = "CONGESTION_SEVERE"
    CONGESTION_UNKNOWN = "CONGESTION_UNKNOWN"


class ChainHeatPayloadQualityLabel(StrEnum):
    CHAIN_HEAT_CONTEXT_CLEAN = "CHAIN_HEAT_CONTEXT_CLEAN"
    CHAIN_HEAT_CONTEXT_PARTIAL = "CHAIN_HEAT_CONTEXT_PARTIAL"
    CHAIN_HEAT_CONTEXT_STALE = "CHAIN_HEAT_CONTEXT_STALE"
    CHAIN_HEAT_CONTEXT_CONFLICTING = "CHAIN_HEAT_CONTEXT_CONFLICTING"
    CHAIN_HEAT_CONTEXT_UNKNOWN = "CHAIN_HEAT_CONTEXT_UNKNOWN"
    CHAIN_HEAT_CONTEXT_DO_NOT_USE_FOR_MEMORY = "CHAIN_HEAT_CONTEXT_DO_NOT_USE_FOR_MEMORY"
