"""Memory Retrieval contracts for Printer V1 Phase 15."""

from enum import StrEnum


class RetrievalQueryTypeLabel(StrEnum):
    CURRENT_SETUP_QUERY = "CURRENT_SETUP_QUERY"
    TOKEN_PAIR_HISTORY_QUERY = "TOKEN_PAIR_HISTORY_QUERY"
    OUTCOME_LOOKBACK_QUERY = "OUTCOME_LOOKBACK_QUERY"
    CLEAN_MEMORY_ONLY_QUERY = "CLEAN_MEMORY_ONLY_QUERY"
    AUDIT_MEMORY_REVIEW_QUERY = "AUDIT_MEMORY_REVIEW_QUERY"


class MatchStrengthLabel(StrEnum):
    EXACT_CONDITION_MATCH = "EXACT_CONDITION_MATCH"
    STRONG_CONDITION_MATCH = "STRONG_CONDITION_MATCH"
    PARTIAL_CONDITION_MATCH = "PARTIAL_CONDITION_MATCH"
    WEAK_CONDITION_MATCH = "WEAK_CONDITION_MATCH"
    NO_USABLE_MATCH = "NO_USABLE_MATCH"
    DIRTY_MEMORY_EXCLUDED = "DIRTY_MEMORY_EXCLUDED"
    DO_NOT_TRAIN_EXCLUDED = "DO_NOT_TRAIN_EXCLUDED"


class MatchReasonLabel(StrEnum):
    MATCH_WINDOW_KIND = "MATCH_WINDOW_KIND"
    MATCH_OUTCOME_LABEL = "MATCH_OUTCOME_LABEL"
    MATCH_MARKET_REGIME = "MATCH_MARKET_REGIME"
    MATCH_CHAIN_HEAT = "MATCH_CHAIN_HEAT"
    MATCH_SAFETY_CONTEXT = "MATCH_SAFETY_CONTEXT"
    MATCH_LIQUIDITY_EXIT_CONTEXT = "MATCH_LIQUIDITY_EXIT_CONTEXT"
    MATCH_TRADING_FLOW_CONTEXT = "MATCH_TRADING_FLOW_CONTEXT"
    MATCH_CHART_VOLATILITY_CONTEXT = "MATCH_CHART_VOLATILITY_CONTEXT"
    MATCH_MICRO_EVENT_SUPPORT = "MATCH_MICRO_EVENT_SUPPORT"
    MATCH_TOKEN_AGE_BUCKET = "MATCH_TOKEN_AGE_BUCKET"
    MATCH_PAIR_AGE_BUCKET = "MATCH_PAIR_AGE_BUCKET"
    MATCH_DISCOVERY_CONTEXT = "MATCH_DISCOVERY_CONTEXT"
    MISMATCH_OUTCOME_LABEL = "MISMATCH_OUTCOME_LABEL"
    MISMATCH_SAFETY_CONTEXT = "MISMATCH_SAFETY_CONTEXT"
    MISMATCH_LIQUIDITY_EXIT_CONTEXT = "MISMATCH_LIQUIDITY_EXIT_CONTEXT"
    MISMATCH_TRADING_FLOW_CONTEXT = "MISMATCH_TRADING_FLOW_CONTEXT"
    MISMATCH_CHART_CONTEXT = "MISMATCH_CHART_CONTEXT"
    MISSING_CURRENT_CONTEXT = "MISSING_CURRENT_CONTEXT"
    MISSING_MEMORY_CONTEXT = "MISSING_MEMORY_CONTEXT"


class RetrievalResultLabel(StrEnum):
    RETRIEVAL_HAS_CLEAN_MATCHES = "RETRIEVAL_HAS_CLEAN_MATCHES"
    RETRIEVAL_HAS_PARTIAL_MATCHES_ONLY = "RETRIEVAL_HAS_PARTIAL_MATCHES_ONLY"
    RETRIEVAL_HAS_AUDIT_ONLY_MATCHES = "RETRIEVAL_HAS_AUDIT_ONLY_MATCHES"
    RETRIEVAL_NO_MATCHES = "RETRIEVAL_NO_MATCHES"
    RETRIEVAL_BLOCKED_NO_CLEAN_MEMORY = "RETRIEVAL_BLOCKED_NO_CLEAN_MEMORY"
    RETRIEVAL_BLOCKED_DIRTY_CURRENT_CONTEXT = "RETRIEVAL_BLOCKED_DIRTY_CURRENT_CONTEXT"


class MemoryEvidenceLabel(StrEnum):
    MEMORY_EVIDENCE_STRONG = "MEMORY_EVIDENCE_STRONG"
    MEMORY_EVIDENCE_MIXED = "MEMORY_EVIDENCE_MIXED"
    MEMORY_EVIDENCE_WEAK = "MEMORY_EVIDENCE_WEAK"
    MEMORY_EVIDENCE_CONFLICTING = "MEMORY_EVIDENCE_CONFLICTING"
    MEMORY_EVIDENCE_NOT_ENOUGH = "MEMORY_EVIDENCE_NOT_ENOUGH"
