"""Micro-Event contracts for Printer V1 Phase 13."""

from enum import StrEnum


class MicroEventStateLabel(StrEnum):
    NO_MICRO_EVENT = "NO_MICRO_EVENT"
    FAST_MICRO_PUMP = "FAST_MICRO_PUMP"
    TRADABLE_MICRO_PUMP = "TRADABLE_MICRO_PUMP"
    UNTRADABLE_MICRO_PUMP = "UNTRADABLE_MICRO_PUMP"
    FAKE_PUMP_WITH_EXIT = "FAKE_PUMP_WITH_EXIT"
    FAKE_PUMP_NO_EXIT = "FAKE_PUMP_NO_EXIT"
    FAST_PUMP_DUMP = "FAST_PUMP_DUMP"
    WICK_PUMP = "WICK_PUMP"
    WICK_ONLY_PUMP = "WICK_ONLY_PUMP"
    LATE_BUY_TRAP = "LATE_BUY_TRAP"
    MICRO_PUMP_TO_SUSTAINED_PUMP = "MICRO_PUMP_TO_SUSTAINED_PUMP"
    MICRO_PUMP_TO_CONSOLIDATION = "MICRO_PUMP_TO_CONSOLIDATION"
    MICRO_PUMP_TO_DEAD_TOKEN = "MICRO_PUMP_TO_DEAD_TOKEN"
    MICRO_EVENT_UNKNOWN = "MICRO_EVENT_UNKNOWN"


class MicroEventMoveLabel(StrEnum):
    MOVE_FAST_UP = "MOVE_FAST_UP"
    MOVE_FAST_DOWN = "MOVE_FAST_DOWN"
    MOVE_SPIKE_AND_HOLD = "MOVE_SPIKE_AND_HOLD"
    MOVE_SPIKE_AND_FADE = "MOVE_SPIKE_AND_FADE"
    MOVE_WICK_ONLY = "MOVE_WICK_ONLY"
    MOVE_ROUND_TRIP = "MOVE_ROUND_TRIP"
    MOVE_NO_CLEAR_EVENT = "MOVE_NO_CLEAR_EVENT"
    MOVE_UNKNOWN = "MOVE_UNKNOWN"


class MicroExitRealismLabel(StrEnum):
    MICRO_EXIT_REALISTIC = "MICRO_EXIT_REALISTIC"
    MICRO_EXIT_POSSIBLE_WITH_SLIPPAGE = "MICRO_EXIT_POSSIBLE_WITH_SLIPPAGE"
    MICRO_EXIT_FRAGILE = "MICRO_EXIT_FRAGILE"
    MICRO_EXIT_UNREALISTIC = "MICRO_EXIT_UNREALISTIC"
    MICRO_EXIT_NO_EXIT = "MICRO_EXIT_NO_EXIT"
    MICRO_EXIT_UNKNOWN = "MICRO_EXIT_UNKNOWN"


class LateBuyTrapLabel(StrEnum):
    NO_LATE_BUY_TRAP = "NO_LATE_BUY_TRAP"
    POSSIBLE_LATE_BUY_TRAP = "POSSIBLE_LATE_BUY_TRAP"
    CONFIRMED_LATE_BUY_TRAP = "CONFIRMED_LATE_BUY_TRAP"
    LATE_BUY_TRAP_UNKNOWN = "LATE_BUY_TRAP_UNKNOWN"


class HeldTo15mResultLabel(StrEnum):
    HELD_TO_15M_CONTINUED = "HELD_TO_15M_CONTINUED"
    HELD_TO_15M_CONSOLIDATED = "HELD_TO_15M_CONSOLIDATED"
    HELD_TO_15M_FADED = "HELD_TO_15M_FADED"
    HELD_TO_15M_DUMPED = "HELD_TO_15M_DUMPED"
    HELD_TO_15M_DEAD = "HELD_TO_15M_DEAD"
    HELD_TO_15M_UNKNOWN = "HELD_TO_15M_UNKNOWN"


class MicroEventPayloadQualityLabel(StrEnum):
    MICRO_EVENT_CONTEXT_CLEAN = "MICRO_EVENT_CONTEXT_CLEAN"
    MICRO_EVENT_CONTEXT_PARTIAL = "MICRO_EVENT_CONTEXT_PARTIAL"
    MICRO_EVENT_CONTEXT_STALE = "MICRO_EVENT_CONTEXT_STALE"
    MICRO_EVENT_CONTEXT_CONFLICTING = "MICRO_EVENT_CONTEXT_CONFLICTING"
    MICRO_EVENT_CONTEXT_UNKNOWN = "MICRO_EVENT_CONTEXT_UNKNOWN"
    MICRO_EVENT_CONTEXT_DO_NOT_USE_FOR_MEMORY = "MICRO_EVENT_CONTEXT_DO_NOT_USE_FOR_MEMORY"


class MicroEventMemoryGateLabel(StrEnum):
    MICRO_EVENT_SUPPORT_EVIDENCE = "MICRO_EVENT_SUPPORT_EVIDENCE"
    MICRO_EVENT_AUDIT_ONLY = "MICRO_EVENT_AUDIT_ONLY"
    MICRO_EVENT_DO_NOT_TRAIN = "MICRO_EVENT_DO_NOT_TRAIN"
    MICRO_EVENT_IGNORE = "MICRO_EVENT_IGNORE"
