"""Operator review contracts for Printer V1 Phase 19."""

from enum import StrEnum


class ReportScopeLabel(StrEnum):
    REPORT_DB_STATE = "REPORT_DB_STATE"
    REPORT_SYSTEM_HEALTH = "REPORT_SYSTEM_HEALTH"
    REPORT_SOURCE_HEALTH = "REPORT_SOURCE_HEALTH"
    REPORT_SCHEDULER_HEALTH = "REPORT_SCHEDULER_HEALTH"
    REPORT_LIFECYCLE_QUEUE = "REPORT_LIFECYCLE_QUEUE"
    REPORT_DISCOVERY = "REPORT_DISCOVERY"
    REPORT_TOKEN_SNAPSHOTS = "REPORT_TOKEN_SNAPSHOTS"
    REPORT_CONTEXT_ENGINES = "REPORT_CONTEXT_ENGINES"
    REPORT_MEMORY = "REPORT_MEMORY"
    REPORT_MEMORY_RETRIEVAL = "REPORT_MEMORY_RETRIEVAL"
    REPORT_PAPER_DECISIONS = "REPORT_PAPER_DECISIONS"
    REPORT_PAPER_POSITIONS = "REPORT_PAPER_POSITIONS"
    REPORT_PAPER_AUDITS = "REPORT_PAPER_AUDITS"
    REPORT_FULL_OPERATOR_REVIEW = "REPORT_FULL_OPERATOR_REVIEW"
    REPORT_UNKNOWN_SCOPE = "REPORT_UNKNOWN_SCOPE"


class ReportStatusLabel(StrEnum):
    REPORT_READY = "REPORT_READY"
    REPORT_PARTIAL = "REPORT_PARTIAL"
    REPORT_EMPTY = "REPORT_EMPTY"
    REPORT_STALE = "REPORT_STALE"
    REPORT_CONFLICTING = "REPORT_CONFLICTING"
    REPORT_FAILED = "REPORT_FAILED"
    REPORT_NO_DB = "REPORT_NO_DB"
    REPORT_SCHEMA_ONLY = "REPORT_SCHEMA_ONLY"
    REPORT_UNKNOWN = "REPORT_UNKNOWN"


class OperatorReviewLabel(StrEnum):
    OPERATOR_REVIEW_OK = "OPERATOR_REVIEW_OK"
    OPERATOR_REVIEW_NEEDS_ATTENTION = "OPERATOR_REVIEW_NEEDS_ATTENTION"
    OPERATOR_REVIEW_BLOCKED = "OPERATOR_REVIEW_BLOCKED"
    OPERATOR_REVIEW_AUDIT_ONLY = "OPERATOR_REVIEW_AUDIT_ONLY"
    OPERATOR_REVIEW_NO_DB = "OPERATOR_REVIEW_NO_DB"
    OPERATOR_REVIEW_SCHEMA_ONLY = "OPERATOR_REVIEW_SCHEMA_ONLY"
    OPERATOR_REVIEW_NO_DATA = "OPERATOR_REVIEW_NO_DATA"
    OPERATOR_REVIEW_UNKNOWN = "OPERATOR_REVIEW_UNKNOWN"


class OperatorAttentionLabel(StrEnum):
    ATTENTION_NONE = "ATTENTION_NONE"
    ATTENTION_NO_PERSISTENT_DB = "ATTENTION_NO_PERSISTENT_DB"
    ATTENTION_SCHEMA_ONLY_DB = "ATTENTION_SCHEMA_ONLY_DB"
    ATTENTION_SOURCE_FAILURES = "ATTENTION_SOURCE_FAILURES"
    ATTENTION_SCHEDULER_BACKLOG = "ATTENTION_SCHEDULER_BACKLOG"
    ATTENTION_STALE_SNAPSHOTS = "ATTENTION_STALE_SNAPSHOTS"
    ATTENTION_BROKEN_MEMORY_WINDOWS = "ATTENTION_BROKEN_MEMORY_WINDOWS"
    ATTENTION_DIRTY_MEMORY = "ATTENTION_DIRTY_MEMORY"
    ATTENTION_NO_CLEAN_MEMORY = "ATTENTION_NO_CLEAN_MEMORY"
    ATTENTION_BLOCKED_PAPER_DECISIONS = "ATTENTION_BLOCKED_PAPER_DECISIONS"
    ATTENTION_OPEN_PAPER_POSITION = "ATTENTION_OPEN_PAPER_POSITION"
    ATTENTION_PAPER_EXIT_RISK = "ATTENTION_PAPER_EXIT_RISK"
    ATTENTION_PAPER_AUDIT_FAILURE = "ATTENTION_PAPER_AUDIT_FAILURE"
    ATTENTION_DATA_QUALITY_ISSUE = "ATTENTION_DATA_QUALITY_ISSUE"
    ATTENTION_UNKNOWN = "ATTENTION_UNKNOWN"


class ReportFormatLabel(StrEnum):
    REPORT_FORMAT_JSON = "REPORT_FORMAT_JSON"
    REPORT_FORMAT_MARKDOWN = "REPORT_FORMAT_MARKDOWN"
    REPORT_FORMAT_TEXT = "REPORT_FORMAT_TEXT"
