"""Discovery labels for Printer V1 Phase 5."""

from enum import StrEnum


class DiscoveryPayloadState(StrEnum):
    VALID_PAYLOAD = "VALID_PAYLOAD"
    PARTIAL_PAYLOAD = "PARTIAL_PAYLOAD"
    MISSING_CRITICAL_FIELDS = "MISSING_CRITICAL_FIELDS"
    UNSUPPORTED_CHAIN = "UNSUPPORTED_CHAIN"
    UNSUPPORTED_PAIR = "UNSUPPORTED_PAIR"
    STALE_SOURCE_DATA = "STALE_SOURCE_DATA"
    CONFLICTING_SOURCE_DATA = "CONFLICTING_SOURCE_DATA"


class DiscoveryCandidateLabel(StrEnum):
    NEW_CANDIDATE = "NEW_CANDIDATE"
    EXISTING_TOKEN_NEW_PAIR = "EXISTING_TOKEN_NEW_PAIR"
    EXISTING_TOKEN_EXISTING_PAIR = "EXISTING_TOKEN_EXISTING_PAIR"
    DUPLICATE_IGNORED = "DUPLICATE_IGNORED"
    INSTANT_REJECT = "INSTANT_REJECT"
    WATCH_ONLY_CANDIDATE = "WATCH_ONLY_CANDIDATE"
    TRACK_NORMAL_CANDIDATE = "TRACK_NORMAL_CANDIDATE"
    TRACK_FAST_CANDIDATE = "TRACK_FAST_CANDIDATE"


class DiscoveryOutputAction(StrEnum):
    IGNORE = "IGNORE"
    WATCH_ONLY = "WATCH_ONLY"
    TRACK_NORMAL = "TRACK_NORMAL"
    TRACK_FAST = "TRACK_FAST"
    INSTANT_REJECT_MEMORY_ONLY = "INSTANT_REJECT_MEMORY_ONLY"


DISCOVERY_PAYLOAD_STATES = tuple(DiscoveryPayloadState)
DISCOVERY_CANDIDATE_LABELS = tuple(DiscoveryCandidateLabel)
DISCOVERY_OUTPUT_ACTIONS = tuple(DiscoveryOutputAction)
