"""Chart / Volatility contracts for Printer V1 Phase 12."""

from enum import StrEnum


class TrendStructureLabel(StrEnum):
    TREND_UP = "TREND_UP"
    TREND_DOWN = "TREND_DOWN"
    TREND_SIDEWAYS = "TREND_SIDEWAYS"
    TREND_PARABOLIC_UP = "TREND_PARABOLIC_UP"
    TREND_PARABOLIC_DOWN = "TREND_PARABOLIC_DOWN"
    TREND_CHOPPY = "TREND_CHOPPY"
    TREND_UNKNOWN = "TREND_UNKNOWN"


class VolatilityLabel(StrEnum):
    VOLATILITY_LOW = "VOLATILITY_LOW"
    VOLATILITY_NORMAL = "VOLATILITY_NORMAL"
    VOLATILITY_ELEVATED = "VOLATILITY_ELEVATED"
    VOLATILITY_HIGH = "VOLATILITY_HIGH"
    VOLATILITY_EXTREME = "VOLATILITY_EXTREME"
    VOLATILITY_UNKNOWN = "VOLATILITY_UNKNOWN"


class RangeBehaviorLabel(StrEnum):
    RANGE_EXPANDING = "RANGE_EXPANDING"
    RANGE_COMPRESSING = "RANGE_COMPRESSING"
    RANGE_BREAKOUT = "RANGE_BREAKOUT"
    RANGE_BREAKDOWN = "RANGE_BREAKDOWN"
    RANGE_FAKEOUT = "RANGE_FAKEOUT"
    RANGE_UNKNOWN = "RANGE_UNKNOWN"


class MomentumLabel(StrEnum):
    MOMENTUM_ACCELERATING_UP = "MOMENTUM_ACCELERATING_UP"
    MOMENTUM_ACCELERATING_DOWN = "MOMENTUM_ACCELERATING_DOWN"
    MOMENTUM_FADING = "MOMENTUM_FADING"
    MOMENTUM_STABLE = "MOMENTUM_STABLE"
    MOMENTUM_EXHAUSTED = "MOMENTUM_EXHAUSTED"
    MOMENTUM_UNKNOWN = "MOMENTUM_UNKNOWN"


class DrawdownRecoveryLabel(StrEnum):
    DRAWDOWN_NONE = "DRAWDOWN_NONE"
    DRAWDOWN_MINOR = "DRAWDOWN_MINOR"
    DRAWDOWN_MODERATE = "DRAWDOWN_MODERATE"
    DRAWDOWN_SEVERE = "DRAWDOWN_SEVERE"
    RECOVERY_STRONG = "RECOVERY_STRONG"
    RECOVERY_WEAK = "RECOVERY_WEAK"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    DRAWDOWN_RECOVERY_UNKNOWN = "DRAWDOWN_RECOVERY_UNKNOWN"


class CandlePathLabel(StrEnum):
    PATH_STEADY_CLIMB = "PATH_STEADY_CLIMB"
    PATH_SPIKE_AND_HOLD = "PATH_SPIKE_AND_HOLD"
    PATH_SPIKE_AND_FADE = "PATH_SPIKE_AND_FADE"
    PATH_GRIND_DOWN = "PATH_GRIND_DOWN"
    PATH_V_SHAPED_RECOVERY = "PATH_V_SHAPED_RECOVERY"
    PATH_ROUND_TRIP = "PATH_ROUND_TRIP"
    PATH_CHOPPY_NOISE = "PATH_CHOPPY_NOISE"
    PATH_UNKNOWN = "PATH_UNKNOWN"


class ChartPayloadQualityLabel(StrEnum):
    CHART_CONTEXT_CLEAN = "CHART_CONTEXT_CLEAN"
    CHART_CONTEXT_PARTIAL = "CHART_CONTEXT_PARTIAL"
    CHART_CONTEXT_STALE = "CHART_CONTEXT_STALE"
    CHART_CONTEXT_CONFLICTING = "CHART_CONTEXT_CONFLICTING"
    CHART_CONTEXT_UNKNOWN = "CHART_CONTEXT_UNKNOWN"
    CHART_CONTEXT_DO_NOT_USE_FOR_MEMORY = "CHART_CONTEXT_DO_NOT_USE_FOR_MEMORY"


class ChartMemoryGateLabel(StrEnum):
    CHART_CONTEXT_ACCEPTABLE = "CHART_CONTEXT_ACCEPTABLE"
    CHART_CONTEXT_CAUTION = "CHART_CONTEXT_CAUTION"
    CHART_CONTEXT_AUDIT_ONLY = "CHART_CONTEXT_AUDIT_ONLY"
    CHART_CONTEXT_DO_NOT_TRAIN = "CHART_CONTEXT_DO_NOT_TRAIN"
