"""Paper Decision contracts for Printer V1 Phase 16."""

from enum import StrEnum

from printer_v1.contracts.enums import PaperAction


class PaperDecisionActionLabel(StrEnum):
    BUY = PaperAction.BUY.value
    SELL = PaperAction.SELL.value
    HOLD = PaperAction.HOLD.value
    WAIT = PaperAction.WAIT.value
    AVOID = PaperAction.AVOID.value
    NO_ACTION = PaperAction.NO_ACTION.value


class DecisionGateLabel(StrEnum):
    DECISION_ALLOWED = "DECISION_ALLOWED"
    DECISION_BLOCKED_NO_CLEAN_MEMORY = "DECISION_BLOCKED_NO_CLEAN_MEMORY"
    DECISION_BLOCKED_DIRTY_CURRENT_CONTEXT = "DECISION_BLOCKED_DIRTY_CURRENT_CONTEXT"
    DECISION_BLOCKED_UNSAFE_TOKEN = "DECISION_BLOCKED_UNSAFE_TOKEN"
    DECISION_BLOCKED_UNREALISTIC_EXIT = "DECISION_BLOCKED_UNREALISTIC_EXIT"
    DECISION_BLOCKED_NO_ROUTE = "DECISION_BLOCKED_NO_ROUTE"
    DECISION_BLOCKED_STALE_DATA = "DECISION_BLOCKED_STALE_DATA"
    DECISION_BLOCKED_CONFLICTING_DATA = "DECISION_BLOCKED_CONFLICTING_DATA"
    DECISION_BLOCKED_INSUFFICIENT_EVIDENCE = "DECISION_BLOCKED_INSUFFICIENT_EVIDENCE"
    DECISION_AUDIT_ONLY = "DECISION_AUDIT_ONLY"


class MemoryEvidenceGateLabel(StrEnum):
    MEMORY_GATE_CLEAN_MATCH = "MEMORY_GATE_CLEAN_MATCH"
    MEMORY_GATE_MIXED_MATCH = "MEMORY_GATE_MIXED_MATCH"
    MEMORY_GATE_WEAK_MATCH = "MEMORY_GATE_WEAK_MATCH"
    MEMORY_GATE_NO_MATCH = "MEMORY_GATE_NO_MATCH"
    MEMORY_GATE_DIRTY_ONLY = "MEMORY_GATE_DIRTY_ONLY"
    MEMORY_GATE_BLOCKED = "MEMORY_GATE_BLOCKED"


class PaperDecisionReasonLabel(StrEnum):
    REASON_CLEAN_MEMORY_MATCH_SUPPORTS_ACTION = "REASON_CLEAN_MEMORY_MATCH_SUPPORTS_ACTION"
    REASON_HISTORICAL_OUTCOMES_SUPPORT_ACTION = "REASON_HISTORICAL_OUTCOMES_SUPPORT_ACTION"
    REASON_SAFETY_CONTEXT_BLOCKS_ACTION = "REASON_SAFETY_CONTEXT_BLOCKS_ACTION"
    REASON_LIQUIDITY_EXIT_BLOCKS_ACTION = "REASON_LIQUIDITY_EXIT_BLOCKS_ACTION"
    REASON_TRADING_FLOW_BLOCKS_ACTION = "REASON_TRADING_FLOW_BLOCKS_ACTION"
    REASON_CHART_CONTEXT_BLOCKS_ACTION = "REASON_CHART_CONTEXT_BLOCKS_ACTION"
    REASON_MICRO_EVENT_SUPPORTS_CAUTION = "REASON_MICRO_EVENT_SUPPORTS_CAUTION"
    REASON_MARKET_CONTEXT_SUPPORTS_CAUTION = "REASON_MARKET_CONTEXT_SUPPORTS_CAUTION"
    REASON_CHAIN_HEAT_SUPPORTS_CAUTION = "REASON_CHAIN_HEAT_SUPPORTS_CAUTION"
    REASON_CONTEXT_CONFLICT = "REASON_CONTEXT_CONFLICT"
    REASON_NOT_ENOUGH_CLEAN_MEMORY = "REASON_NOT_ENOUGH_CLEAN_MEMORY"
    REASON_DATA_STALE = "REASON_DATA_STALE"
    REASON_DATA_CONFLICTING = "REASON_DATA_CONFLICTING"
    REASON_AUDIT_ONLY = "REASON_AUDIT_ONLY"


class PaperDecisionStatusLabel(StrEnum):
    PAPER_DECISION_PROPOSED = "PAPER_DECISION_PROPOSED"
    PAPER_DECISION_BLOCKED = "PAPER_DECISION_BLOCKED"
    PAPER_DECISION_AUDIT_ONLY = "PAPER_DECISION_AUDIT_ONLY"
    PAPER_DECISION_EXPIRED = "PAPER_DECISION_EXPIRED"
    PAPER_DECISION_SUPERSEDED = "PAPER_DECISION_SUPERSEDED"
