"""Token lifecycle contracts for Printer V1 Phase 4."""

from enum import StrEnum


class TokenLifecycleState(StrEnum):
    DISCOVERED = "DISCOVERED"
    WATCH_ONLY = "WATCH_ONLY"
    TRACK_NORMAL = "TRACK_NORMAL"
    TRACK_FAST = "TRACK_FAST"
    PAPER_MONITORING = "PAPER_MONITORING"
    COOLDOWN = "COOLDOWN"
    ARCHIVED = "ARCHIVED"
    INSTANT_REJECT_MEMORY_ONLY = "INSTANT_REJECT_MEMORY_ONLY"


class LifecycleEvent(StrEnum):
    NEW_DISCOVERY = "NEW_DISCOVERY"
    PROMOTE_TO_TRACK_FAST = "PROMOTE_TO_TRACK_FAST"
    PROMOTE_TO_TRACK_NORMAL = "PROMOTE_TO_TRACK_NORMAL"
    DEMOTE_TO_WATCH_ONLY = "DEMOTE_TO_WATCH_ONLY"
    ENTER_PAPER_MONITORING = "ENTER_PAPER_MONITORING"
    ENTER_COOLDOWN = "ENTER_COOLDOWN"
    ARCHIVE_STALE_TOKEN = "ARCHIVE_STALE_TOKEN"
    ARCHIVE_UNUSABLE_LIQUIDITY = "ARCHIVE_UNUSABLE_LIQUIDITY"
    ARCHIVE_AFTER_MEMORY_WINDOW = "ARCHIVE_AFTER_MEMORY_WINDOW"
    REOPEN_REVIVED_TOKEN = "REOPEN_REVIVED_TOKEN"
    INSTANT_REJECT_BAD_DATA = "INSTANT_REJECT_BAD_DATA"
    INSTANT_REJECT_UNSUPPORTED_CHAIN = "INSTANT_REJECT_UNSUPPORTED_CHAIN"
    INSTANT_REJECT_UNUSABLE_PAIR = "INSTANT_REJECT_UNUSABLE_PAIR"
    WATCH_ONLY_REFRESH = "WATCH_ONLY_REFRESH"
    SOURCE_DATA_STALE = "SOURCE_DATA_STALE"
    SOURCE_DATA_CONFLICTING = "SOURCE_DATA_CONFLICTING"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class QueueStatus(StrEnum):
    QUEUED = "QUEUED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COOLDOWN = "COOLDOWN"
    ARCHIVED = "ARCHIVED"
    SKIPPED = "SKIPPED"


LIFECYCLE_EVENTS = tuple(LifecycleEvent)
QUEUE_STATUS_ORDER = tuple(QueueStatus)
TRACKING_LANE_DUE_ORDER = (
    TokenLifecycleState.PAPER_MONITORING,
    TokenLifecycleState.TRACK_FAST,
    TokenLifecycleState.TRACK_NORMAL,
    TokenLifecycleState.WATCH_ONLY,
    TokenLifecycleState.COOLDOWN,
)
