"""Market regime contracts for Printer V1 Phase 7."""

from enum import StrEnum


class MarketRegimeLabel(StrEnum):
    EXTREME_FEAR = "EXTREME_FEAR"
    FEAR = "FEAR"
    NEUTRAL = "NEUTRAL"
    GREED = "GREED"
    EXTREME_GREED = "EXTREME_GREED"
    RISK_ON = "RISK_ON"
    RISK_OFF = "RISK_OFF"
    CHOPPY = "CHOPPY"
    VOLATILE = "VOLATILE"
    UNKNOWN = "UNKNOWN"


class MarketTransitionLabel(StrEnum):
    FEAR_TO_NEUTRAL = "FEAR_TO_NEUTRAL"
    NEUTRAL_TO_GREED = "NEUTRAL_TO_GREED"
    GREED_TO_EXTREME_GREED = "GREED_TO_EXTREME_GREED"
    EXTREME_GREED_TO_GREED = "EXTREME_GREED_TO_GREED"
    GREED_TO_NEUTRAL = "GREED_TO_NEUTRAL"
    NEUTRAL_TO_FEAR = "NEUTRAL_TO_FEAR"
    FEAR_TO_EXTREME_FEAR = "FEAR_TO_EXTREME_FEAR"
    RISK_OFF_TO_RISK_ON = "RISK_OFF_TO_RISK_ON"
    RISK_ON_TO_RISK_OFF = "RISK_ON_TO_RISK_OFF"
    CHOPPY_TO_TRENDING = "CHOPPY_TO_TRENDING"
    TRENDING_TO_CHOPPY = "TRENDING_TO_CHOPPY"
    UNKNOWN_TRANSITION = "UNKNOWN_TRANSITION"


class MarketPayloadQualityLabel(StrEnum):
    MARKET_CONTEXT_CLEAN = "MARKET_CONTEXT_CLEAN"
    MARKET_CONTEXT_PARTIAL = "MARKET_CONTEXT_PARTIAL"
    MARKET_CONTEXT_STALE = "MARKET_CONTEXT_STALE"
    MARKET_CONTEXT_CONFLICTING = "MARKET_CONTEXT_CONFLICTING"
    MARKET_CONTEXT_UNKNOWN = "MARKET_CONTEXT_UNKNOWN"
    MARKET_CONTEXT_DO_NOT_USE_FOR_MEMORY = "MARKET_CONTEXT_DO_NOT_USE_FOR_MEMORY"
