"""Liquidity + Exit contracts for Printer V1 Phase 10."""

from enum import StrEnum


class LiquidityStateLabel(StrEnum):
    LIQUIDITY_DEEP = "LIQUIDITY_DEEP"
    LIQUIDITY_USABLE = "LIQUIDITY_USABLE"
    LIQUIDITY_THIN = "LIQUIDITY_THIN"
    LIQUIDITY_UNSTABLE = "LIQUIDITY_UNSTABLE"
    LIQUIDITY_DRAINING = "LIQUIDITY_DRAINING"
    LIQUIDITY_DANGEROUS = "LIQUIDITY_DANGEROUS"
    LIQUIDITY_UNKNOWN = "LIQUIDITY_UNKNOWN"


class EntryRealismLabel(StrEnum):
    ENTRY_REALISTIC = "ENTRY_REALISTIC"
    ENTRY_POSSIBLE_WITH_SLIPPAGE = "ENTRY_POSSIBLE_WITH_SLIPPAGE"
    ENTRY_UNREALISTIC = "ENTRY_UNREALISTIC"
    ENTRY_BLOCKED_BY_ROUTE = "ENTRY_BLOCKED_BY_ROUTE"
    ENTRY_UNKNOWN = "ENTRY_UNKNOWN"


class ExitRealismLabel(StrEnum):
    EXIT_REALISTIC = "EXIT_REALISTIC"
    EXIT_POSSIBLE_WITH_SLIPPAGE = "EXIT_POSSIBLE_WITH_SLIPPAGE"
    EXIT_AT_RISK = "EXIT_AT_RISK"
    EXIT_UNREALISTIC = "EXIT_UNREALISTIC"
    EXIT_BLOCKED_BY_ROUTE = "EXIT_BLOCKED_BY_ROUTE"
    EXIT_UNKNOWN = "EXIT_UNKNOWN"


class SlippageLabel(StrEnum):
    SLIPPAGE_LOW = "SLIPPAGE_LOW"
    SLIPPAGE_MODERATE = "SLIPPAGE_MODERATE"
    SLIPPAGE_HIGH = "SLIPPAGE_HIGH"
    SLIPPAGE_EXTREME = "SLIPPAGE_EXTREME"
    SLIPPAGE_UNKNOWN = "SLIPPAGE_UNKNOWN"


class PriceImpactLabel(StrEnum):
    PRICE_IMPACT_LOW = "PRICE_IMPACT_LOW"
    PRICE_IMPACT_MODERATE = "PRICE_IMPACT_MODERATE"
    PRICE_IMPACT_HIGH = "PRICE_IMPACT_HIGH"
    PRICE_IMPACT_EXTREME = "PRICE_IMPACT_EXTREME"
    PRICE_IMPACT_UNKNOWN = "PRICE_IMPACT_UNKNOWN"


class RouteLabel(StrEnum):
    ROUTE_AVAILABLE = "ROUTE_AVAILABLE"
    ROUTE_LIMITED = "ROUTE_LIMITED"
    ROUTE_STALE = "ROUTE_STALE"
    ROUTE_FAILED = "ROUTE_FAILED"
    ROUTE_NOT_AVAILABLE = "ROUTE_NOT_AVAILABLE"
    ROUTE_UNKNOWN = "ROUTE_UNKNOWN"


class QuoteAgeLabel(StrEnum):
    QUOTE_FRESH = "QUOTE_FRESH"
    QUOTE_ACCEPTABLE = "QUOTE_ACCEPTABLE"
    QUOTE_STALE = "QUOTE_STALE"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"
    QUOTE_MISSING = "QUOTE_MISSING"


class LiquidityDrainLabel(StrEnum):
    NO_LIQUIDITY_DRAIN = "NO_LIQUIDITY_DRAIN"
    MINOR_LIQUIDITY_DRAIN = "MINOR_LIQUIDITY_DRAIN"
    MAJOR_LIQUIDITY_DRAIN = "MAJOR_LIQUIDITY_DRAIN"
    SEVERE_LIQUIDITY_DRAIN = "SEVERE_LIQUIDITY_DRAIN"
    LIQUIDITY_DRAIN_UNKNOWN = "LIQUIDITY_DRAIN_UNKNOWN"


class LiquidityExitPayloadQualityLabel(StrEnum):
    LIQUIDITY_EXIT_CONTEXT_CLEAN = "LIQUIDITY_EXIT_CONTEXT_CLEAN"
    LIQUIDITY_EXIT_CONTEXT_PARTIAL = "LIQUIDITY_EXIT_CONTEXT_PARTIAL"
    LIQUIDITY_EXIT_CONTEXT_STALE = "LIQUIDITY_EXIT_CONTEXT_STALE"
    LIQUIDITY_EXIT_CONTEXT_CONFLICTING = "LIQUIDITY_EXIT_CONTEXT_CONFLICTING"
    LIQUIDITY_EXIT_CONTEXT_UNKNOWN = "LIQUIDITY_EXIT_CONTEXT_UNKNOWN"
    LIQUIDITY_EXIT_CONTEXT_DO_NOT_USE_FOR_MEMORY = "LIQUIDITY_EXIT_CONTEXT_DO_NOT_USE_FOR_MEMORY"


class RealismGateLabel(StrEnum):
    REALISM_CONTEXT_ACCEPTABLE = "REALISM_CONTEXT_ACCEPTABLE"
    REALISM_CONTEXT_CAUTION = "REALISM_CONTEXT_CAUTION"
    REALISM_CONTEXT_BLOCKED = "REALISM_CONTEXT_BLOCKED"
    REALISM_CONTEXT_AUDIT_ONLY = "REALISM_CONTEXT_AUDIT_ONLY"
    REALISM_CONTEXT_DO_NOT_TRAIN = "REALISM_CONTEXT_DO_NOT_TRAIN"
