from pathlib import Path

path = Path("src/printer_v1/operator_cli/operational_memory_factory_command.py")
text = path.read_text(encoding="utf-8")
old = '''        # Read the four external manifest/marker bindings once and all-or-none.\n        # Ordinary run is application-wrapper-only; auxiliary modes preserve\n        # their existing no-binding behavior.\n        git_provenance_authorization = _resolve_git_provenance_authorization(args.mode)\n        if args.mode == "run" and git_provenance_authorization is None:\n            raise OperationalMemoryFactoryError(\n                "ordinary run requires external one-shot wrapper authorization"\n            )\n        if args.mode == "run":\n            child_terminal_binding = resolve_child_terminal_binding(os.environ)\n        elif os.environ.get(CHILD_TERMINAL_ENV_VAR):\n            raise OperationalMemoryFactoryError(\n                "child terminal binding is accepted only for ordinary run"\n            )\n'''
new = '''        # Preserve the original direct-run fail-closed classification when no\n        # wrapper provenance bindings exist. A valid wrapper supplies all four\n        # values; only then establish reporting before their deeper validation\n        # so a provenance mismatch can still emit structured terminal evidence.\n        provenance_binding_values = tuple(\n            os.environ.get(name) for name in GIT_PROVENANCE_MANIFEST_ENV_VARS\n        )\n        if args.mode == "run" and not any(provenance_binding_values):\n            raise OperationalMemoryFactoryError(\n                "ordinary run requires external one-shot wrapper authorization"\n            )\n        if args.mode == "run" and all(provenance_binding_values):\n            child_terminal_binding = resolve_child_terminal_binding(os.environ)\n        elif args.mode != "run" and os.environ.get(CHILD_TERMINAL_ENV_VAR):\n            raise OperationalMemoryFactoryError(\n                "child terminal binding is accepted only for ordinary run"\n            )\n        # Read the four external manifest/marker bindings once and all-or-none.\n        # Ordinary run is application-wrapper-only; auxiliary modes preserve\n        # their existing no-binding behavior.\n        git_provenance_authorization = _resolve_git_provenance_authorization(args.mode)\n        if args.mode == "run" and git_provenance_authorization is None:\n            raise OperationalMemoryFactoryError(\n                "ordinary run requires external one-shot wrapper authorization"\n            )\n        if args.mode == "run" and child_terminal_binding is None:\n            raise OperationalMemoryFactoryError(\n                "ordinary run child terminal binding requires complete wrapper provenance"\n            )\n'''
if text.count(old) != 1:
    raise SystemExit(
        f"provenance/binding call-order anchor mismatch: {text.count(old)}"
    )
path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("provenance reporting-binding call order repaired")
