"""Paper Trade Monitor contracts for Printer V1 Phase 17."""

from enum import StrEnum


class PaperPositionStatusLabel(StrEnum):
    PAPER_POSITION_PENDING_ENTRY = "PAPER_POSITION_PENDING_ENTRY"
    PAPER_POSITION_OPEN = "PAPER_POSITION_OPEN"
    PAPER_POSITION_MONITORING = "PAPER_POSITION_MONITORING"
    PAPER_POSITION_EXIT_WATCH = "PAPER_POSITION_EXIT_WATCH"
    PAPER_POSITION_CLOSED = "PAPER_POSITION_CLOSED"
    PAPER_POSITION_CANCELLED = "PAPER_POSITION_CANCELLED"
    PAPER_POSITION_BLOCKED = "PAPER_POSITION_BLOCKED"
    PAPER_POSITION_EXPIRED = "PAPER_POSITION_EXPIRED"


class PaperEntryStatusLabel(StrEnum):
    PAPER_ENTRY_ALLOWED = "PAPER_ENTRY_ALLOWED"
    PAPER_ENTRY_BLOCKED_NO_DECISION = "PAPER_ENTRY_BLOCKED_NO_DECISION"
    PAPER_ENTRY_BLOCKED_DECISION_NOT_ALLOWED = "PAPER_ENTRY_BLOCKED_DECISION_NOT_ALLOWED"
    PAPER_ENTRY_BLOCKED_NOT_BUY_ACTION = "PAPER_ENTRY_BLOCKED_NOT_BUY_ACTION"
    PAPER_ENTRY_BLOCKED_STALE_CONTEXT = "PAPER_ENTRY_BLOCKED_STALE_CONTEXT"
    PAPER_ENTRY_BLOCKED_UNREALISTIC_ENTRY = "PAPER_ENTRY_BLOCKED_UNREALISTIC_ENTRY"
    PAPER_ENTRY_BLOCKED_UNSAFE_TOKEN = "PAPER_ENTRY_BLOCKED_UNSAFE_TOKEN"
    PAPER_ENTRY_AUDIT_ONLY = "PAPER_ENTRY_AUDIT_ONLY"


class PaperMonitorStateLabel(StrEnum):
    MONITOR_HEALTHY = "MONITOR_HEALTHY"
    MONITOR_PROFIT_WATCH = "MONITOR_PROFIT_WATCH"
    MONITOR_DRAWDOWN_WATCH = "MONITOR_DRAWDOWN_WATCH"
    MONITOR_EXIT_RISK = "MONITOR_EXIT_RISK"
    MONITOR_ROUTE_RISK = "MONITOR_ROUTE_RISK"
    MONITOR_LIQUIDITY_RISK = "MONITOR_LIQUIDITY_RISK"
    MONITOR_SAFETY_RISK = "MONITOR_SAFETY_RISK"
    MONITOR_STALE_DATA = "MONITOR_STALE_DATA"
    MONITOR_CLOSED = "MONITOR_CLOSED"
    MONITOR_UNKNOWN = "MONITOR_UNKNOWN"


class PaperExitReasonLabel(StrEnum):
    EXIT_REASON_TARGET_REACHED = "EXIT_REASON_TARGET_REACHED"
    EXIT_REASON_STOP_REACHED = "EXIT_REASON_STOP_REACHED"
    EXIT_REASON_TRAILING_DRAWDOWN = "EXIT_REASON_TRAILING_DRAWDOWN"
    EXIT_REASON_LIQUIDITY_EXIT_RISK = "EXIT_REASON_LIQUIDITY_EXIT_RISK"
    EXIT_REASON_ROUTE_FAILED = "EXIT_REASON_ROUTE_FAILED"
    EXIT_REASON_SAFETY_RISK = "EXIT_REASON_SAFETY_RISK"
    EXIT_REASON_MEMORY_INVALIDATION = "EXIT_REASON_MEMORY_INVALIDATION"
    EXIT_REASON_TIME_EXPIRY = "EXIT_REASON_TIME_EXPIRY"
    EXIT_REASON_MANUAL_AUDIT = "EXIT_REASON_MANUAL_AUDIT"
    EXIT_REASON_NO_EXIT = "EXIT_REASON_NO_EXIT"


class PaperPnlStateLabel(StrEnum):
    PNL_UNREALIZED_PROFIT = "PNL_UNREALIZED_PROFIT"
    PNL_UNREALIZED_LOSS = "PNL_UNREALIZED_LOSS"
    PNL_REALIZED_PROFIT = "PNL_REALIZED_PROFIT"
    PNL_REALIZED_LOSS = "PNL_REALIZED_LOSS"
    PNL_BREAKEVEN = "PNL_BREAKEVEN"
    PNL_UNKNOWN = "PNL_UNKNOWN"


class PaperTradeEventLabel(StrEnum):
    PAPER_EVENT_ENTRY_CREATED = "PAPER_EVENT_ENTRY_CREATED"
    PAPER_EVENT_ENTRY_BLOCKED = "PAPER_EVENT_ENTRY_BLOCKED"
    PAPER_EVENT_POSITION_OPENED = "PAPER_EVENT_POSITION_OPENED"
    PAPER_EVENT_SNAPSHOT_MONITORED = "PAPER_EVENT_SNAPSHOT_MONITORED"
    PAPER_EVENT_EXIT_RISK_DETECTED = "PAPER_EVENT_EXIT_RISK_DETECTED"
    PAPER_EVENT_POSITION_CLOSED = "PAPER_EVENT_POSITION_CLOSED"
    PAPER_EVENT_POSITION_EXPIRED = "PAPER_EVENT_POSITION_EXPIRED"
    PAPER_EVENT_AUDIT_RECORDED = "PAPER_EVENT_AUDIT_RECORDED"


class PaperMonitorQualityLabel(StrEnum):
    PAPER_MONITOR_CONTEXT_CLEAN = "PAPER_MONITOR_CONTEXT_CLEAN"
    PAPER_MONITOR_CONTEXT_PARTIAL = "PAPER_MONITOR_CONTEXT_PARTIAL"
    PAPER_MONITOR_CONTEXT_STALE = "PAPER_MONITOR_CONTEXT_STALE"
    PAPER_MONITOR_CONTEXT_CONFLICTING = "PAPER_MONITOR_CONTEXT_CONFLICTING"
    PAPER_MONITOR_CONTEXT_UNKNOWN = "PAPER_MONITOR_CONTEXT_UNKNOWN"
    PAPER_MONITOR_CONTEXT_DO_NOT_USE = "PAPER_MONITOR_CONTEXT_DO_NOT_USE"
