"""Paper Audit contracts for Printer V1 Phase 18."""

from enum import StrEnum


class PaperAuditScopeLabel(StrEnum):
    AUDIT_PAPER_DECISION = "AUDIT_PAPER_DECISION"
    AUDIT_PAPER_ENTRY = "AUDIT_PAPER_ENTRY"
    AUDIT_PAPER_MONITORING = "AUDIT_PAPER_MONITORING"
    AUDIT_PAPER_EXIT = "AUDIT_PAPER_EXIT"
    AUDIT_PAPER_PNL = "AUDIT_PAPER_PNL"
    AUDIT_RULE_COMPLIANCE = "AUDIT_RULE_COMPLIANCE"
    AUDIT_FULL_PAPER_TRADE = "AUDIT_FULL_PAPER_TRADE"
    AUDIT_UNKNOWN_SCOPE = "AUDIT_UNKNOWN_SCOPE"


class PaperAuditResultLabel(StrEnum):
    PAPER_AUDIT_PASS = "PAPER_AUDIT_PASS"
    PAPER_AUDIT_PASS_WITH_WARNINGS = "PAPER_AUDIT_PASS_WITH_WARNINGS"
    PAPER_AUDIT_FAIL = "PAPER_AUDIT_FAIL"
    PAPER_AUDIT_INCOMPLETE = "PAPER_AUDIT_INCOMPLETE"
    PAPER_AUDIT_AUDIT_ONLY = "PAPER_AUDIT_AUDIT_ONLY"
    PAPER_AUDIT_UNKNOWN = "PAPER_AUDIT_UNKNOWN"


class PaperRuleComplianceLabel(StrEnum):
    RULES_COMPLIANT = "RULES_COMPLIANT"
    RULES_COMPLIANT_WITH_WARNINGS = "RULES_COMPLIANT_WITH_WARNINGS"
    RULES_VIOLATION = "RULES_VIOLATION"
    RULES_INCOMPLETE_EVIDENCE = "RULES_INCOMPLETE_EVIDENCE"
    RULES_UNKNOWN = "RULES_UNKNOWN"


class PaperRealismLabel(StrEnum):
    PAPER_REALISM_CLEAN = "PAPER_REALISM_CLEAN"
    PAPER_REALISM_ACCEPTABLE = "PAPER_REALISM_ACCEPTABLE"
    PAPER_REALISM_WEAK = "PAPER_REALISM_WEAK"
    PAPER_REALISM_UNREALISTIC = "PAPER_REALISM_UNREALISTIC"
    PAPER_REALISM_UNKNOWN = "PAPER_REALISM_UNKNOWN"


class PaperOutcomeReviewLabel(StrEnum):
    PAPER_OUTCOME_WORKED = "PAPER_OUTCOME_WORKED"
    PAPER_OUTCOME_FAILED = "PAPER_OUTCOME_FAILED"
    PAPER_OUTCOME_PROTECTED_CAPITAL = "PAPER_OUTCOME_PROTECTED_CAPITAL"
    PAPER_OUTCOME_MISSED_UPSIDE = "PAPER_OUTCOME_MISSED_UPSIDE"
    PAPER_OUTCOME_NO_ACTION_VALID = "PAPER_OUTCOME_NO_ACTION_VALID"
    PAPER_OUTCOME_INCONCLUSIVE = "PAPER_OUTCOME_INCONCLUSIVE"
    PAPER_OUTCOME_UNKNOWN = "PAPER_OUTCOME_UNKNOWN"


class PaperDataQualityAuditLabel(StrEnum):
    PAPER_AUDIT_DATA_CLEAN = "PAPER_AUDIT_DATA_CLEAN"
    PAPER_AUDIT_DATA_PARTIAL = "PAPER_AUDIT_DATA_PARTIAL"
    PAPER_AUDIT_DATA_STALE = "PAPER_AUDIT_DATA_STALE"
    PAPER_AUDIT_DATA_CONFLICTING = "PAPER_AUDIT_DATA_CONFLICTING"
    PAPER_AUDIT_DATA_MISSING = "PAPER_AUDIT_DATA_MISSING"
    PAPER_AUDIT_DATA_UNKNOWN = "PAPER_AUDIT_DATA_UNKNOWN"


class PaperAuditIssueLabel(StrEnum):
    ISSUE_NO_VALID_DECISION = "ISSUE_NO_VALID_DECISION"
    ISSUE_POSITION_WITHOUT_DECISION = "ISSUE_POSITION_WITHOUT_DECISION"
    ISSUE_BLOCKED_DECISION_OPENED = "ISSUE_BLOCKED_DECISION_OPENED"
    ISSUE_NON_BUY_DECISION_OPENED = "ISSUE_NON_BUY_DECISION_OPENED"
    ISSUE_STALE_ENTRY_CONTEXT = "ISSUE_STALE_ENTRY_CONTEXT"
    ISSUE_UNREALISTIC_ENTRY = "ISSUE_UNREALISTIC_ENTRY"
    ISSUE_UNREALISTIC_EXIT = "ISSUE_UNREALISTIC_EXIT"
    ISSUE_UNSAFE_CONTEXT_IGNORED = "ISSUE_UNSAFE_CONTEXT_IGNORED"
    ISSUE_ROUTE_RISK_IGNORED = "ISSUE_ROUTE_RISK_IGNORED"
    ISSUE_LIQUIDITY_RISK_IGNORED = "ISSUE_LIQUIDITY_RISK_IGNORED"
    ISSUE_MONITORING_GAP = "ISSUE_MONITORING_GAP"
    ISSUE_MISSING_CLOSE_EVIDENCE = "ISSUE_MISSING_CLOSE_EVIDENCE"
    ISSUE_PNL_INCONSISTENT = "ISSUE_PNL_INCONSISTENT"
    ISSUE_REALISM_WEAK = "ISSUE_REALISM_WEAK"
    ISSUE_NONE = "ISSUE_NONE"
