"""Trading Flow contracts for Printer V1 Phase 11."""

from enum import StrEnum


class FlowDirectionLabel(StrEnum):
    FLOW_ACCUMULATION = "FLOW_ACCUMULATION"
    FLOW_DISTRIBUTION = "FLOW_DISTRIBUTION"
    FLOW_ROTATION = "FLOW_ROTATION"
    FLOW_EXHAUSTION = "FLOW_EXHAUSTION"
    FLOW_CHOPPY = "FLOW_CHOPPY"
    FLOW_WASH_LIKE = "FLOW_WASH_LIKE"
    FLOW_UNKNOWN = "FLOW_UNKNOWN"


class FlowPressureLabel(StrEnum):
    PRESSURE_STRONG_INFLOW = "PRESSURE_STRONG_INFLOW"
    PRESSURE_MODERATE_INFLOW = "PRESSURE_MODERATE_INFLOW"
    PRESSURE_BALANCED = "PRESSURE_BALANCED"
    PRESSURE_MODERATE_OUTFLOW = "PRESSURE_MODERATE_OUTFLOW"
    PRESSURE_STRONG_OUTFLOW = "PRESSURE_STRONG_OUTFLOW"
    PRESSURE_UNKNOWN = "PRESSURE_UNKNOWN"


class ImbalanceLabel(StrEnum):
    IMBALANCE_BUY_HEAVY = "IMBALANCE_BUY_HEAVY"
    IMBALANCE_SELL_HEAVY = "IMBALANCE_SELL_HEAVY"
    IMBALANCE_BALANCED = "IMBALANCE_BALANCED"
    IMBALANCE_NOISY = "IMBALANCE_NOISY"
    IMBALANCE_UNKNOWN = "IMBALANCE_UNKNOWN"


class VolumeActivityLabel(StrEnum):
    VOLUME_SURGING = "VOLUME_SURGING"
    VOLUME_ELEVATED = "VOLUME_ELEVATED"
    VOLUME_NORMAL = "VOLUME_NORMAL"
    VOLUME_WEAK = "VOLUME_WEAK"
    VOLUME_DEAD = "VOLUME_DEAD"
    VOLUME_UNKNOWN = "VOLUME_UNKNOWN"


class TxActivityLabel(StrEnum):
    TX_ACTIVITY_SURGING = "TX_ACTIVITY_SURGING"
    TX_ACTIVITY_ELEVATED = "TX_ACTIVITY_ELEVATED"
    TX_ACTIVITY_NORMAL = "TX_ACTIVITY_NORMAL"
    TX_ACTIVITY_WEAK = "TX_ACTIVITY_WEAK"
    TX_ACTIVITY_DEAD = "TX_ACTIVITY_DEAD"
    TX_ACTIVITY_UNKNOWN = "TX_ACTIVITY_UNKNOWN"


class WalletParticipationLabel(StrEnum):
    WALLETS_BROAD_PARTICIPATION = "WALLETS_BROAD_PARTICIPATION"
    WALLETS_NARROW_PARTICIPATION = "WALLETS_NARROW_PARTICIPATION"
    WALLETS_CONCENTRATED = "WALLETS_CONCENTRATED"
    WALLETS_WASH_LIKE = "WALLETS_WASH_LIKE"
    WALLETS_UNKNOWN = "WALLETS_UNKNOWN"


class TradingFlowPayloadQualityLabel(StrEnum):
    TRADING_FLOW_CONTEXT_CLEAN = "TRADING_FLOW_CONTEXT_CLEAN"
    TRADING_FLOW_CONTEXT_PARTIAL = "TRADING_FLOW_CONTEXT_PARTIAL"
    TRADING_FLOW_CONTEXT_STALE = "TRADING_FLOW_CONTEXT_STALE"
    TRADING_FLOW_CONTEXT_CONFLICTING = "TRADING_FLOW_CONTEXT_CONFLICTING"
    TRADING_FLOW_CONTEXT_UNKNOWN = "TRADING_FLOW_CONTEXT_UNKNOWN"
    TRADING_FLOW_CONTEXT_DO_NOT_USE_FOR_MEMORY = "TRADING_FLOW_CONTEXT_DO_NOT_USE_FOR_MEMORY"


class FlowMemoryGateLabel(StrEnum):
    FLOW_CONTEXT_ACCEPTABLE = "FLOW_CONTEXT_ACCEPTABLE"
    FLOW_CONTEXT_CAUTION = "FLOW_CONTEXT_CAUTION"
    FLOW_CONTEXT_AUDIT_ONLY = "FLOW_CONTEXT_AUDIT_ONLY"
    FLOW_CONTEXT_DO_NOT_TRAIN = "FLOW_CONTEXT_DO_NOT_TRAIN"
