"""Episode / Memory contracts for Printer V1 Phase 14."""

from enum import StrEnum


class MemoryWindowKind(StrEnum):
    WINDOW_5M_MICRO_EVENT = "WINDOW_5M_MICRO_EVENT"
    WINDOW_15M = "WINDOW_15M"
    WINDOW_1H = "WINDOW_1H"
    WINDOW_4H = "WINDOW_4H"
    WINDOW_12H = "WINDOW_12H"
    WINDOW_24H = "WINDOW_24H"


class MemoryWindowStatus(StrEnum):
    WINDOW_OPEN = "WINDOW_OPEN"
    WINDOW_CLOSING = "WINDOW_CLOSING"
    WINDOW_CLOSED = "WINDOW_CLOSED"
    WINDOW_BROKEN = "WINDOW_BROKEN"
    WINDOW_SKIPPED = "WINDOW_SKIPPED"
    WINDOW_AUDIT_ONLY = "WINDOW_AUDIT_ONLY"


class EpisodeStatus(StrEnum):
    EPISODE_BUILDABLE = "EPISODE_BUILDABLE"
    EPISODE_BUILT = "EPISODE_BUILT"
    EPISODE_DIRTY = "EPISODE_DIRTY"
    EPISODE_AUDIT_ONLY = "EPISODE_AUDIT_ONLY"
    EPISODE_SKIPPED = "EPISODE_SKIPPED"
    EPISODE_INCOMPLETE = "EPISODE_INCOMPLETE"


class EpisodeOutcomeLabel(StrEnum):
    NO_PUMP = "NO_PUMP"
    FAKE_PUMP = "FAKE_PUMP"
    SHORT_TERM_PUMP = "SHORT_TERM_PUMP"
    SUSTAINED_PUMP = "SUSTAINED_PUMP"
    EXTENDED_PUMP = "EXTENDED_PUMP"
    CONSOLIDATION = "CONSOLIDATION"
    DUMP = "DUMP"
    PUMP_AND_DUMP = "PUMP_AND_DUMP"
    ROUND_TRIP = "ROUND_TRIP"
    REVIVAL = "REVIVAL"
    DEAD_TOKEN = "DEAD_TOKEN"
    UNREALISTIC_PROFIT = "UNREALISTIC_PROFIT"
    REALISTIC_PAPER_PROFIT = "REALISTIC_PAPER_PROFIT"
    REALISTIC_CAPITAL_PROTECTION = "REALISTIC_CAPITAL_PROTECTION"
    MISSED_UPSIDE = "MISSED_UPSIDE"
    OUTCOME_UNKNOWN = "OUTCOME_UNKNOWN"


class MemoryQualityLabel(StrEnum):
    CLEAN_MEMORY = "CLEAN_MEMORY"
    PARTIAL_MEMORY = "PARTIAL_MEMORY"
    DIRTY_MEMORY = "DIRTY_MEMORY"
    AUDIT_ONLY_MEMORY = "AUDIT_ONLY_MEMORY"
    DO_NOT_TRAIN_MEMORY = "DO_NOT_TRAIN_MEMORY"


class MemoryRejectionReasonLabel(StrEnum):
    REJECT_MISSING_SNAPSHOTS = "REJECT_MISSING_SNAPSHOTS"
    REJECT_BROKEN_COVERAGE = "REJECT_BROKEN_COVERAGE"
    REJECT_STALE_SOURCE_DATA = "REJECT_STALE_SOURCE_DATA"
    REJECT_CONFLICTING_DATA = "REJECT_CONFLICTING_DATA"
    REJECT_MISSING_CRITICAL_FIELDS = "REJECT_MISSING_CRITICAL_FIELDS"
    REJECT_UNREALISTIC_EXIT = "REJECT_UNREALISTIC_EXIT"
    REJECT_UNSAFE_TOKEN = "REJECT_UNSAFE_TOKEN"
    REJECT_DIRTY_SAFETY_CONTEXT = "REJECT_DIRTY_SAFETY_CONTEXT"
    REJECT_DIRTY_LIQUIDITY_CONTEXT = "REJECT_DIRTY_LIQUIDITY_CONTEXT"
    REJECT_DIRTY_FLOW_CONTEXT = "REJECT_DIRTY_FLOW_CONTEXT"
    REJECT_DIRTY_CHART_CONTEXT = "REJECT_DIRTY_CHART_CONTEXT"
    REJECT_DIRTY_MARKET_CONTEXT = "REJECT_DIRTY_MARKET_CONTEXT"
    REJECT_DIRTY_CHAIN_HEAT_CONTEXT = "REJECT_DIRTY_CHAIN_HEAT_CONTEXT"
    REJECT_5M_ONLY_WINDOW = "REJECT_5M_ONLY_WINDOW"
    REJECT_UNKNOWN_OUTCOME = "REJECT_UNKNOWN_OUTCOME"
    REJECT_MANUAL_REVIEW_REQUIRED = "REJECT_MANUAL_REVIEW_REQUIRED"


class ActionLessonLabel(StrEnum):
    ACTION_BUY_WORKED = "ACTION_BUY_WORKED"
    ACTION_BUY_FAILED = "ACTION_BUY_FAILED"
    ACTION_WAIT_WORKED = "ACTION_WAIT_WORKED"
    ACTION_WAIT_FAILED = "ACTION_WAIT_FAILED"
    ACTION_AVOID_WORKED = "ACTION_AVOID_WORKED"
    ACTION_AVOID_FAILED = "ACTION_AVOID_FAILED"
    ACTION_HOLD_WORKED = "ACTION_HOLD_WORKED"
    ACTION_HOLD_FAILED = "ACTION_HOLD_FAILED"
    ACTION_SELL_WORKED = "ACTION_SELL_WORKED"
    ACTION_SELL_FAILED = "ACTION_SELL_FAILED"
    ACTION_NO_ACTION_WORKED = "ACTION_NO_ACTION_WORKED"
    ACTION_NO_ACTION_FAILED = "ACTION_NO_ACTION_FAILED"
    ACTION_LESSON_UNKNOWN = "ACTION_LESSON_UNKNOWN"
