"""Phase 20 validation labels."""

from enum import StrEnum


class ValidationScopeLabel(StrEnum):
    VALIDATION_SCHEMA = "VALIDATION_SCHEMA"
    VALIDATION_CONTRACTS = "VALIDATION_CONTRACTS"
    VALIDATION_MIGRATIONS = "VALIDATION_MIGRATIONS"
    VALIDATION_SYNTHETIC_DISCOVERY = "VALIDATION_SYNTHETIC_DISCOVERY"
    VALIDATION_SYNTHETIC_SNAPSHOTS = "VALIDATION_SYNTHETIC_SNAPSHOTS"
    VALIDATION_SYNTHETIC_CONTEXT = "VALIDATION_SYNTHETIC_CONTEXT"
    VALIDATION_SYNTHETIC_MEMORY = "VALIDATION_SYNTHETIC_MEMORY"
    VALIDATION_SYNTHETIC_RETRIEVAL = "VALIDATION_SYNTHETIC_RETRIEVAL"
    VALIDATION_SYNTHETIC_PAPER_DECISION = "VALIDATION_SYNTHETIC_PAPER_DECISION"
    VALIDATION_SYNTHETIC_PAPER_MONITOR = "VALIDATION_SYNTHETIC_PAPER_MONITOR"
    VALIDATION_SYNTHETIC_PAPER_AUDIT = "VALIDATION_SYNTHETIC_PAPER_AUDIT"
    VALIDATION_SYNTHETIC_OPERATOR_REPORT = "VALIDATION_SYNTHETIC_OPERATOR_REPORT"
    VALIDATION_FULL_SYNTHETIC_FLOW = "VALIDATION_FULL_SYNTHETIC_FLOW"
    VALIDATION_UNKNOWN_SCOPE = "VALIDATION_UNKNOWN_SCOPE"


class ValidationResultLabel(StrEnum):
    VALIDATION_PASS = "VALIDATION_PASS"
    VALIDATION_PASS_WITH_WARNINGS = "VALIDATION_PASS_WITH_WARNINGS"
    VALIDATION_FAIL = "VALIDATION_FAIL"
    VALIDATION_SKIPPED = "VALIDATION_SKIPPED"
    VALIDATION_INCOMPLETE = "VALIDATION_INCOMPLETE"
    VALIDATION_UNKNOWN = "VALIDATION_UNKNOWN"


class ValidationIssueLabel(StrEnum):
    VALIDATION_ISSUE_NONE = "VALIDATION_ISSUE_NONE"
    VALIDATION_ISSUE_MISSING_TABLE = "VALIDATION_ISSUE_MISSING_TABLE"
    VALIDATION_ISSUE_MISSING_COLUMN = "VALIDATION_ISSUE_MISSING_COLUMN"
    VALIDATION_ISSUE_FORBIDDEN_COLUMN = "VALIDATION_ISSUE_FORBIDDEN_COLUMN"
    VALIDATION_ISSUE_LABEL_MISMATCH = "VALIDATION_ISSUE_LABEL_MISMATCH"
    VALIDATION_ISSUE_MIGRATION_FAILURE = "VALIDATION_ISSUE_MIGRATION_FAILURE"
    VALIDATION_ISSUE_DIRTY_MEMORY_ALLOWED = "VALIDATION_ISSUE_DIRTY_MEMORY_ALLOWED"
    VALIDATION_ISSUE_DECISION_WITHOUT_CLEAN_MEMORY = "VALIDATION_ISSUE_DECISION_WITHOUT_CLEAN_MEMORY"
    VALIDATION_ISSUE_POSITION_WITHOUT_VALID_DECISION = "VALIDATION_ISSUE_POSITION_WITHOUT_VALID_DECISION"
    VALIDATION_ISSUE_LIVE_CAPABILITY_FOUND = "VALIDATION_ISSUE_LIVE_CAPABILITY_FOUND"
    VALIDATION_ISSUE_RUNTIME_LOOP_FOUND = "VALIDATION_ISSUE_RUNTIME_LOOP_FOUND"
    VALIDATION_ISSUE_PROJECT_DB_CREATED_IN_TEST = "VALIDATION_ISSUE_PROJECT_DB_CREATED_IN_TEST"
    VALIDATION_ISSUE_UNKNOWN = "VALIDATION_ISSUE_UNKNOWN"


class SyntheticFlowStageLabel(StrEnum):
    FLOW_STAGE_DB_INIT = "FLOW_STAGE_DB_INIT"
    FLOW_STAGE_DISCOVERY = "FLOW_STAGE_DISCOVERY"
    FLOW_STAGE_SNAPSHOTS = "FLOW_STAGE_SNAPSHOTS"
    FLOW_STAGE_CONTEXT = "FLOW_STAGE_CONTEXT"
    FLOW_STAGE_MEMORY = "FLOW_STAGE_MEMORY"
    FLOW_STAGE_RETRIEVAL = "FLOW_STAGE_RETRIEVAL"
    FLOW_STAGE_PAPER_DECISION = "FLOW_STAGE_PAPER_DECISION"
    FLOW_STAGE_PAPER_POSITION = "FLOW_STAGE_PAPER_POSITION"
    FLOW_STAGE_PAPER_MONITOR = "FLOW_STAGE_PAPER_MONITOR"
    FLOW_STAGE_PAPER_AUDIT = "FLOW_STAGE_PAPER_AUDIT"
    FLOW_STAGE_OPERATOR_REVIEW = "FLOW_STAGE_OPERATOR_REVIEW"
    FLOW_STAGE_COMPLETE = "FLOW_STAGE_COMPLETE"
    FLOW_STAGE_UNKNOWN = "FLOW_STAGE_UNKNOWN"


VALIDATION_SCOPE_LABELS = {label.value for label in ValidationScopeLabel}
VALIDATION_RESULT_LABELS = {label.value for label in ValidationResultLabel}
VALIDATION_ISSUE_LABELS = {label.value for label in ValidationIssueLabel}
SYNTHETIC_FLOW_STAGE_LABELS = {label.value for label in SyntheticFlowStageLabel}
