"""Safety / Rug Filter contracts for Printer V1 Phase 9."""

from enum import StrEnum


class SafetyStatusLabel(StrEnum):
    SAFETY_CLEAN = "SAFETY_CLEAN"
    SAFETY_CAUTION = "SAFETY_CAUTION"
    SAFETY_SUSPICIOUS = "SAFETY_SUSPICIOUS"
    SAFETY_UNSAFE = "SAFETY_UNSAFE"
    SAFETY_UNKNOWN = "SAFETY_UNKNOWN"
    SAFETY_DO_NOT_USE_FOR_MEMORY = "SAFETY_DO_NOT_USE_FOR_MEMORY"


class RugRiskLabel(StrEnum):
    RUG_RISK_LOW = "RUG_RISK_LOW"
    RUG_RISK_MEDIUM = "RUG_RISK_MEDIUM"
    RUG_RISK_HIGH = "RUG_RISK_HIGH"
    RUG_RISK_CRITICAL = "RUG_RISK_CRITICAL"
    RUG_RISK_UNKNOWN = "RUG_RISK_UNKNOWN"


class LiquiditySafetyLabel(StrEnum):
    LIQUIDITY_SAFE = "LIQUIDITY_SAFE"
    LIQUIDITY_THIN = "LIQUIDITY_THIN"
    LIQUIDITY_UNSTABLE = "LIQUIDITY_UNSTABLE"
    LIQUIDITY_LOCK_UNKNOWN = "LIQUIDITY_LOCK_UNKNOWN"
    LIQUIDITY_DANGEROUS = "LIQUIDITY_DANGEROUS"
    LIQUIDITY_SAFETY_UNKNOWN = "LIQUIDITY_SAFETY_UNKNOWN"


class AuthorityLabel(StrEnum):
    AUTHORITY_RENOUNCED_OR_SAFE = "AUTHORITY_RENOUNCED_OR_SAFE"
    AUTHORITY_PRESENT = "AUTHORITY_PRESENT"
    AUTHORITY_SUSPICIOUS = "AUTHORITY_SUSPICIOUS"
    AUTHORITY_DANGEROUS = "AUTHORITY_DANGEROUS"
    AUTHORITY_UNKNOWN = "AUTHORITY_UNKNOWN"


class DistributionLabel(StrEnum):
    DISTRIBUTION_HEALTHY = "DISTRIBUTION_HEALTHY"
    DISTRIBUTION_CONCENTRATED = "DISTRIBUTION_CONCENTRATED"
    DISTRIBUTION_EXTREME_CONCENTRATION = "DISTRIBUTION_EXTREME_CONCENTRATION"
    DISTRIBUTION_UNKNOWN = "DISTRIBUTION_UNKNOWN"


class SafetyPayloadQualityLabel(StrEnum):
    SAFETY_CONTEXT_CLEAN = "SAFETY_CONTEXT_CLEAN"
    SAFETY_CONTEXT_PARTIAL = "SAFETY_CONTEXT_PARTIAL"
    SAFETY_CONTEXT_STALE = "SAFETY_CONTEXT_STALE"
    SAFETY_CONTEXT_CONFLICTING = "SAFETY_CONTEXT_CONFLICTING"
    SAFETY_CONTEXT_UNKNOWN = "SAFETY_CONTEXT_UNKNOWN"
    SAFETY_CONTEXT_DO_NOT_USE_FOR_MEMORY = "SAFETY_CONTEXT_DO_NOT_USE_FOR_MEMORY"


class SafetyGateLabel(StrEnum):
    ALLOW_SAFETY_CONTEXT = "ALLOW_SAFETY_CONTEXT"
    CAUTION_SAFETY_CONTEXT = "CAUTION_SAFETY_CONTEXT"
    BLOCK_UNSAFE_CONTEXT = "BLOCK_UNSAFE_CONTEXT"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    DO_NOT_TRAIN_SAFETY_CONTEXT = "DO_NOT_TRAIN_SAFETY_CONTEXT"
