"""Source registry and governance helpers for Printer V1."""

from printer_v1.sources.contracts import (
    GOVERNOR_ONLY_EXECUTION_PATH,
    MALFORMED_DATA_BEHAVIOR,
    RATE_LIMIT_BEHAVIOR,
    STALE_DATA_BEHAVIOR,
    NormalizedSourceResult,
    SourceAdapterContext,
    SourceAdapterContract,
    SourceFailureRecord,
    SourceRequest,
    SourceRequestRecord,
    SourceResponseRecord,
    build_governed_source_request,
    build_governor_decision,
    build_source_adapter_contract,
    source_request_has_allowed_kind,
    validate_source_adapter_contract,
)
from printer_v1.sources.governed_execution import (
    FIXTURE_FAILURE,
    FIXTURE_MALFORMED,
    FIXTURE_STALE,
    FIXTURE_SUCCESS,
    FixtureSourceAdapter,
    GovernedSourceExecutionResult,
    build_fixture_source_adapter,
    execute_source_request_with_governor,
)
from printer_v1.sources.governor import (
    SourceRequestDecision,
    can_request_source,
    classify_data_quality,
    classify_source_status,
    get_retry_after,
    get_source_definition,
    is_response_stale,
    is_source_allowed,
    normalize_source_payload,
    should_cooldown_source,
    source_priority_value,
    validate_request_kind,
)
from printer_v1.sources.registry import ALLOWED_SOURCE_NAMES, SOURCE_REGISTRY, SourceDefinition

__all__ = [
    "ALLOWED_SOURCE_NAMES",
    "FIXTURE_FAILURE",
    "FIXTURE_MALFORMED",
    "FIXTURE_STALE",
    "FIXTURE_SUCCESS",
    "GOVERNOR_ONLY_EXECUTION_PATH",
    "MALFORMED_DATA_BEHAVIOR",
    "RATE_LIMIT_BEHAVIOR",
    "SOURCE_REGISTRY",
    "STALE_DATA_BEHAVIOR",
    "SourceDefinition",
    "FixtureSourceAdapter",
    "GovernedSourceExecutionResult",
    "NormalizedSourceResult",
    "SourceAdapterContext",
    "SourceAdapterContract",
    "SourceFailureRecord",
    "SourceRequest",
    "SourceRequestDecision",
    "SourceRequestRecord",
    "SourceResponseRecord",
    "build_fixture_source_adapter",
    "build_governed_source_request",
    "build_governor_decision",
    "build_source_adapter_contract",
    "can_request_source",
    "classify_data_quality",
    "classify_source_status",
    "execute_source_request_with_governor",
    "get_retry_after",
    "get_source_definition",
    "is_response_stale",
    "is_source_allowed",
    "normalize_source_payload",
    "should_cooldown_source",
    "source_request_has_allowed_kind",
    "source_priority_value",
    "validate_source_adapter_contract",
    "validate_request_kind",
]
